### 3-1. 네이버 책 검색 API 호출하기

In [ ]:
import requests
import json
from datetime import datetime
import pandas as pd

CLIENT_ID = 'J8fnyyTMFt1eHHqf_zXk'
CLIENT_SECRET = 'VBvhidVVgn'

headers = {
    'X-Naver-Client-Id': CLIENT_ID,
    'X-Naver-Client-Secret': CLIENT_SECRET
}

def search_books(query):
    url = 'https://openapi.naver.com/v1/search/book.json'
    params = {
        'query': query,
        'display': 30,
        'sort': 'sim'
    }
    res = requests.get(url, params=params, headers=headers)
    return res.json()['items']

def save_books_to_json(books, filename='../data/books.json'):
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(books, f)

def load_books_to_dataframe(json_path='../data/books.json'):
    book_df = pd.read_json(json_path)
    return book_df

def preprocess_dataframe(df):
    df = df.copy()
    
    df['description'] = df['description']
    
    return df[['title', 'link', 'image', 'author', 'discount', 
              'publisher', 'pubdate', 'isbn', 'description']]

books = search_books("파이썬")

#### 1. 질문 :  검색어로  찾은  책 목록을 json 파일로 저장하기

In [130]:
save_books_to_json(books)

#### 2. books.json 파일을 Pandas DataFrame로 저장하기

In [131]:
book_df = load_books_to_dataframe()

#### 3. 질문 :  검색어로  찾은  책 목록 출력하기

In [132]:
processed_df = preprocess_dataframe(book_df)
processed_df.head()

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,파이썬,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324609...,홍의경,29440,생능출판,20220309,9788970506784,코딩 실력을 키우는 지름길은 실습이다.\n\n2008년 즈음에 검인정 중학교 교과서...

#### 4. 질문 :  검색어로  찾은  책 목록 중에서 가격이 2만원 이상인 책만 출력하기

In [ ]:
book_df = book_df[book_df['discount'] >= 20000]

book_df_column = book_df[['title', 'author', 'discount', 'publisher', 'pubdate']]
book_df_column_sort = book_df_column.sort_values(by='discount', ascending=False).reset_index(drop=True)

book_df_column_sort.head()

,title,author,discount,publisher,pubdate
0,파이썬,Y. Daniel Liang,31500,에피스테메,20180302
1,으뜸 파이썬 (개정판),박동규^강영민,31280,생능출판,20240614
2,파이썬 마스터 (실생활 융합 예제로 배우는),김종훈^김동건,31040,한빛아카데미,20250117
3,파이썬 머신러닝 완벽 가이드 (다양한 캐글 예제와 함께 기초 알고리즘부터 최신 기법...,권철민,29800,위키북스,20220421
4,파이썬,홍의경,29440,생능출판,20220309

#### 5. 질문 :  검색어로  찾은  책 목록 중에서 출판사가 인피니티북스인 책만 출력하기

In [ ]:
book_df = book_df[book_df['publisher'] == '인피니티북스']

book_df_column = book_df[['title', 'author', 'discount', 'publisher', 'pubdate']]
book_df_column_sort = book_df_column.reset_index(drop=True)

book_df_column_sort.head()

     title author  discount publisher   pubdate
0      파이썬    천인국     12000    인피니티북스  20170830
1  파이썬 플러스    최희식     23750    인피니티북스  20240731

### 3-2. 네이버 쇼핑 검색 API 호출하기

In [ ]:
import requests
import json
import pandas as pd

CLIENT_ID = 'J8fnyyTMFt1eHHqf_zXk'
CLIENT_SECRET = 'VBvhidVVgn'

headers = {
    'X-Naver-Client-Id': CLIENT_ID,
    'X-Naver-Client-Secret': CLIENT_SECRET
}

def search_shops(query):
    params = {
        'query': query,
        'display': 50,
        'sort': 'sim'
    }

    url = 'https://openapi.naver.com/v1/search/shop.json'

    res = requests.get(url, params=params, headers=headers)
    return res.json()['items']

def save_shops_to_json(data, filename='../data/shops.json'):
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(data, f)

def load_shops_to_dataframe(filename='../data/shops.json'):
    return pd.read_json(filename)

shop_data = search_shops('가디건')

#### 1. shops.json 파일을 Pandas DataFrame로 저장하기

In [ ]:
save_shops_to_json(shop_data)

shop_df = load_shops_to_dataframe()

#### 2. 질문 :  검색어로  찾은  Shop의 상품  목록 출력하기

In [ ]:
shop_df_column = [
    'title', 'link', 'image', 'lprice', 'hprice', 'mallName',
    'productId', 'productType', 'brand', 'maker',
    'category1', 'category2', 'category3', 'category4'
]

shop_df[shop_df_column].head()

,title,link,image,lprice,hprice,mallName,productId,productType,brand,maker,category1,category2,category3,category4
0,백화점3-5일배송 폴로 <b>가디건</b> 걸즈 걸스 랄프로렌 꽈배기 블랙 화이트 ...,https://smartstore.naver.com/main/products/667...,https://shopping-phinf.pstatic.net/main_842166...,64900,,나우인뉴욕,84216650390,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,
1,봄 가을 간절기 라운드 루즈핏 크롭 <b>가디건</b> 레드 그린 핑크 화이트 블랙...,https://smartstore.naver.com/main/products/546...,https://shopping-phinf.pstatic.net/main_830114...,19900,,ARUMY,83011442056,2,,,패션의류,여성의류,카디건,
2,부드러운 캐시미어 크롭 <b>가디건</b> 숏 라운드 니트<b>가디건</b> 여성 ...,https://smartstore.naver.com/main/products/482...,https://shopping-phinf.pstatic.net/main_823726...,18900,,코이블리,82372678315,2,,,패션의류,여성의류,카디건,
3,[백화점3-5일배송] 폴로 <b>가디건</b> 니트 걸즈 랄프로렌 블랙 화이트 핑크...,https://smartstore.naver.com/main/products/845...,https://shopping-phinf.pstatic.net/main_859949...,63900,,트위티 155,85994962324,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,
4,[국내발송 + 선물포장] 폴로 랄프로렌 여아 아기 코튼 베이비 <b>가디건</b> ...,https://smartstore.naver.com/main/products/945...,https://shopping-phinf.pstatic.net/main_870040...,69000,,리틀데이즈,87004045841,2,폴로랄프로렌,폴로랄프로렌,출산/육아,유아동의류,카디건,

#### 3. 질문 :  검색어로  찾은  Shop의 상품  목록 중에서 가격이 50,000원 이하인 상품만 출력하기

In [ ]:
shop_df = shop_df[shop_df['lprice'] <= 50000]
shop_df_column = shop_df[['brand', 'lprice', 'mallName', 'link']]
shop_df_column_sort = shop_df_column.sort_values(by='lprice', ascending=True).reset_index(drop=True)

shop_df_column_sort.head()

  brand  lprice mallName                                               link
0   H&M   17512      네이버  https://search.shopping.naver.com/catalog/5178...
1         18900     코이블리  https://smartstore.naver.com/main/products/482...
2         18900     코이블리  https://smartstore.naver.com/main/products/438...
3         19800    로이앤한나  https://smartstore.naver.com/main/products/490...
4         19900    ARUMY  https://smartstore.naver.com/main/products/546...

#### 4. 질문 :  검색어로  찾은  Shop의 상품  목록 중에서 특정 쇼핑몰 상품만 출력하기

In [134]:
shop_df = shop_df[shop_df['mallName'] == '네이버']

shop_df_column = shop_df.loc[:, 'lprice':'brand']
shop_df_column_sort = shop_df_column.sort_values(by='lprice', ascending=True).reset_index(drop=True)

shop_df_column_sort.head()

   lprice hprice mallName    productId  productType     brand
0   17512             네이버  51781610172            1       H&M
1   23000             네이버  51143733510            1       리스트
2   28070             네이버  43475137325            1  비비안웨스트우드
3   29568             네이버  53287208769            1   제너럴아이디어
4   31416             네이버  49541497760            1   제너럴아이디어